<?php

namespace CvBundle\Repository;

/**
 * catTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class catTextRepository extends \Doctrine\ORM\EntityRepository
{
}
