<?php

namespace CvBundle\Repository;

/**
 * skillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class skillRepository extends \Doctrine\ORM\EntityRepository
{
}
