<?php

namespace CvBundle\Repository;

/**
 * texteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class texteRepository extends \Doctrine\ORM\EntityRepository
{
}
