<?php

namespace CvBundle\Repository;

/**
 * txtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class txtRepository extends \Doctrine\ORM\EntityRepository
{
}
